from fastapi import HTTPException, Security, Request
from fastapi.security import HTTPBearer, HTTPAuthorizationCredentials
import jwt
from app.config import settings

security = HTTPBearer()

def verify_supabase_jwt(credentials: HTTPAuthorizationCredentials = Security(security)):
    """Verifies the standard JWT token generated by Supabase GoTrue Auth"""
    token = credentials.credentials
    try:
        # Note: in production, decode and verify signature using the JWT Secret from Supabase Dashboard
        decoded_token = jwt.decode(token, options={"verify_signature": False})
        return decoded_token
    except Exception as e:
        raise HTTPException(status_code=401, detail="Invalid token")
